@startuml usecase
' Use-Case-Diagramm Fahrradverleih Fahradiso: Fahrräder ausleihen (Teil B) mit Login
skinparam packageStyle rectangle
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor #F8F8F8
    BorderColor #555555
}

rectangle "Fahrradverleih Fahradiso" {
    usecase "Registrieren" as UC7
    usecase "Anmelden" as UC8

    usecase "Versicherung\nabschließen" as UC6
    usecase "Sonderzubehör\nmitmieten" as UC5

    usecase "Fahrräder ausleihen" as UC1

    usecase "Verfügbarkeit im\nZeitraum prüfen" as UC2
    usecase "Mietpreis berechnen" as UC3
}

actor "Kunde" as kunde

' Akteur (Linien ohne Pfeilspitze)
kunde -left- UC1
kunde -left- UC8
kunde -left- UC7

' Anmeldung ist Voraussetzung, Registrierung nur bei fehlendem Konto
UC1 .up.> UC8 : <<include>>
UC7 .right.> UC8 : <<extend>>

' Optionale Erweiterungen
UC6 .down.> UC1 : <<extend>>
UC5 .down.> UC1 : <<extend>>

' Pflichtbestandteile
UC1 .down.> UC2 : <<include>>
UC1 .down.> UC3 : <<include>>

@enduml
